# Generated by Django 5.0.6 on 2024-05-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('ID_Artist', models.AutoField(primary_key=True, serialize=False)),
                ('Artist_Name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Chords',
            fields=[
                ('ID_Chord', models.AutoField(primary_key=True, serialize=False)),
                ('Description_Chord', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('ID_Emotion', models.AutoField(primary_key=True, serialize=False)),
                ('Description_Emotion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Emotions',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('ID_Genre', models.AutoField(primary_key=True, serialize=False)),
                ('Genre_Name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('ID_Instrument', models.AutoField(primary_key=True, serialize=False)),
                ('Instrument_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('ID_Key', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('ID_Lyric', models.AutoField(primary_key=True, serialize=False)),
                ('Description_Lyric', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('ID_Album', models.AutoField(primary_key=True, serialize=False)),
                ('Title_Album', models.CharField(default='', max_length=100)),
                ('Release_Date', models.DateField(auto_now_add=True)),
                ('ID_Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.artists')),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('ID_Song', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=100)),
                ('Duration', models.FloatField(default=0.0)),
                ('Release_Date', models.DateField(auto_now_add=True)),
                ('ID_Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.artists')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='LyricFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.lyrics')),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.keys')),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
            options={
                'verbose_name_plural': 'Key Features',
            },
        ),
        migrations.CreateModel(
            name='InstrumentFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.instruments')),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
        ),
        migrations.CreateModel(
            name='GenreFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.genres')),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.emotions')),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dynamic_Level', models.FloatField(default=0.0)),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
            options={
                'verbose_name_plural': 'Dynamic Features',
            },
        ),
        migrations.CreateModel(
            name='ChordFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Chord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.chords')),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
        ),
        migrations.CreateModel(
            name='TempoFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tempo_BPM', models.FloatField(default=0.0)),
                ('ID_Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clave_re.songs')),
            ],
            options={
                'verbose_name_plural': 'Tempo Features',
            },
        ),
    ]
